import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import ThemeProvider from '@/lib/hooks/use-theme';

export const metadata = {
  title: 'artsn-ui',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Counter Program', path: '/counter' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='
        bg-primary text-primary font-sans
        dark:bg-dark dark:text-dark dark:font-sans
        transition-colors duration-200 ease-in-out
      '
      >
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <ThemeProvider>
                <UiLayout links={links}>{children}</UiLayout>
              </ThemeProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
